// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb5zayk9WEB9xSzwF-a2KrhWXh58j6Gfw',
    appId: '1:136279418348:web:cce0eb09c97e992ade8cc9',
    messagingSenderId: '136279418348',
    projectId: 'anogidelivery',
    authDomain: 'anogidelivery.firebaseapp.com',
    storageBucket: 'anogidelivery.firebasestorage.app',
    measurementId: 'G-804H6EF882',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3R5GnYrET_Zje1lrgN6jkpELM9dddtus',
    appId: '1:136279418348:android:99129a19d3a55c58de8cc9',
    messagingSenderId: '136279418348',
    projectId: 'anogidelivery',
    storageBucket: 'anogidelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQy9Y7Vsrv9VLnSum808bQBtdxJszsRbs',
    appId: '1:136279418348:ios:6175de1420041ea7de8cc9',
    messagingSenderId: '136279418348',
    projectId: 'anogidelivery',
    storageBucket: 'anogidelivery.firebasestorage.app',
    iosBundleId: 'com.example.anogiDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQy9Y7Vsrv9VLnSum808bQBtdxJszsRbs',
    appId: '1:136279418348:ios:6175de1420041ea7de8cc9',
    messagingSenderId: '136279418348',
    projectId: 'anogidelivery',
    storageBucket: 'anogidelivery.firebasestorage.app',
    iosBundleId: 'com.example.anogiDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb5zayk9WEB9xSzwF-a2KrhWXh58j6Gfw',
    appId: '1:136279418348:web:435d4cf0476df46cde8cc9',
    messagingSenderId: '136279418348',
    projectId: 'anogidelivery',
    authDomain: 'anogidelivery.firebaseapp.com',
    storageBucket: 'anogidelivery.firebasestorage.app',
    measurementId: 'G-7WP37MPFY5',
  );
}
